[package]
name = "coins-bip32"
version = "0.2.0"
authors = ["James Prestwich <james@prestwi.ch>"]
edition = "2018"
description = "Bip32 (and related BIPs) in Rust"
repository = "https://github.com/summa-tx/bitcoins-rs"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0"
hmac = "0.7.1"
sha2 = "0.8.0"
bs58 = "0.3.0"
lazy_static = "1.4.0"
coins-core = { path = "../core"}
serde = "1.0.105"

k256 = { version = "0.7.1", features = ["std", "ecdsa", "arithmetic"] }

[dev-dependencies]
hex = "0.4.2"
criterion = "0.3.1"

[features]
default = ["mainnet"]
mainnet = []
testnet = []

